---
title: 'Assignment #3'
author: "Josie Shaggy"
date: "September 19, 2018"
output:
  word_document: default
  html_document: default
---

```{r setup}
titanic = read.csv("titanic.csv")
titanic$Survived = factor(titanic$Survived)
titanic$Pclass = factor(titanic$Pclass)
library(ggplot2)
```


1
```{r #1 }

sum(is.na(titanic))

```


2
```{r #2}
sum(is.na(titanic$Age))
mean(titanic$Age, na.rm = TRUE)
titanic$Age[is.na(titanic$Age)] = mean(titanic$Age, na.rm = TRUE)
```
3
```{r #3}
titanic$Cabin= NULL
```

4
```{r #4}
titanic$Name = NULL
titanic$PassengerId = NULL
titanic$Ticket = NULL

```

5
```{r #5}
mean(titanic$Age)

```

6
```{r #6}
mean(titanic[titanic$Sex=="female",]$Age)

```

7
```{r #7}
median(titanic[titanic$Pclass=="1",]$Fare)

```

8
```{r #8}
median(titanic[titanic$Sex=="female" & titanic$Pclass!="1",]$Fare)

```


9
```{r #9}
median(titanic[titanic$Survived == "1" & titanic$Sex=="female" & titanic$Pclass=="1"| titanic$Pclass=="2",]$Age)

```


10
```{r #10}
mean(titanic[(titanic$Survived == "1") & (titanic$Sex == "female") & (titanic$Age>="13" & titanic$Age<="19"),]$Fare)

```


11
```{r #11}
mean(titanic[(titanic$Survived == "1") & (titanic$Sex == "female") & (titanic$Age>="13" & titanic$Age<="19")& (titanic$Pclass == "1"),]$Fare)
mean(titanic[(titanic$Survived == "1") & (titanic$Sex == "female") & (titanic$Age>="13" & titanic$Age<="19")& (titanic$Pclass == "2"),]$Fare)
mean(titanic[(titanic$Survived == "1") & (titanic$Sex == "female") & (titanic$Age>="13" & titanic$Age<="19")& (titanic$Pclass == "3"),]$Fare)
```


12
```{r #12}
t1 = titanic[titanic$Fare>mean(titanic$Fare),]
prop.table(table(t1$Survived))
```


13
```{r #13}
titanic$sfare = (titanic$Fare-mean(titanic$Fare))/sd(titanic$Fare)
```


14
```{r #14}
ggplot(titanic) + geom_bar(data=titanic[titanic$Age< mean(titanic$Age),], mapping = aes(x = Sex, fill = Survived))
```


15
```{r #15}
ggplot(titanic) + geom_density(data=titanic[titanic$Fare>mean(titanic$Fare)&titanic$Survived==1,], mapping = aes(x=Age))
```


16
```{r #16}
ggplot(titanic) + geom_density(data=titanic[(titanic$Embarked=="S")|(titanic$Embarked=="Q"),], mapping = aes(x=Embarked))


```


17
```{r #17}
titanic$cfare = titanic$fare
titanic$cfare[titanic$Fare < mean(titanic$Fare)] = 0
titanic$cfare[titanic$Fare > mean(titanic$Fare)] = 1
titanic$cfare[titanic$Fare < mean(titanic$Fare)] = "cheap"
titanic$cfare[titanic$Fare > mean(titanic$Fare)] = "expensive"

```


18
```{r #18}
titanic$cage =titanic$Age
titanic$cage[titanic$Age <10] = 0
titanic$cage[(titanic$Age > 10)&(titanic$Age < 20)] = 1
titanic$cage[(titanic$Age > 20)&(titanic$Age < 30)] = 2
titanic$cage[(titanic$Age > 30)&(titanic$Age <40)] = 3
titanic$cage[(titanic$Age > 40)&(titanic$Age <50)] = 4
titanic$cage[(titanic$Age > 50)&(titanic$Age< 60)] = 5
titanic$cage[(titanic$Age > 60)&(titanic$Age< 70)] = 6
titanic$cage[(titanic$Age > 70)&(titanic$Age< 80)] = 7
titanic$cage[(titanic$Age > 80)&(titanic$Age < 90)] = 8



```


19
```{r #19}
ggplot(titanic) + geom_bar(data=titanic[titanic$Fare>mean(titanic$Fare)&titanic$Survived==1,], mapping = aes(x=cage))
```

20
```{r #20}
ggplot(titanic) + geom_bar(data=titanic[titanic$Fare>mean(titanic$Fare)&titanic$Survived==1,], mapping = aes(x=cage))+
 facet_wrap(~ Pclass)
```